In [2]:
import sys
import pandas as pd
import numpy as np

print("Python:", sys.version)
print("Python executable:", sys.executable)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Python: 3.13.11 | packaged by Anaconda, Inc. | (main, Dec 10 2025, 21:21:58) [MSC v.1929 64 bit (AMD64)]
Python executable: c:\Users\Administrator\Documents\AI_AMR_Healthcare_Project\.venv\Scripts\python.exe
Pandas: 3.0.6
NumPy: 2.5.3

In [3]:
from pathlib import Path
import pandas as pd

data_path = Path("../data/raw")

culture_file = data_path / "microbiology_cultures_cohort.csv"
demographics_file = data_path / "microbiology_cultures_demographics.csv"

culture_sample = pd.read_csv(culture_file, nrows=5)
demographics_sample = pd.read_csv(demographics_file, nrows=5)

print("CULTURE DATA")
print("Columns:", culture_sample.columns.tolist())
print("\nFirst 5 rows:")
display(culture_sample)

print("\n" + "=" * 80)

print("DEMOGRAPHICS DATA")
print("Columns:", demographics_sample.columns.tolist())
print("\nFirst 5 rows:")
display(demographics_sample)

CULTURE DATA
Columns: ['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'order_time_jittered', 'ordering_mode', 'culture_description', 'was_positive', 'organism', 'antibiotic', 'susceptibility']

First 5 rows:

,anon_id,pat_enc_csn_id_coded,order_proc_id_coded,order_time_jittered,ordering_mode,culture_description,was_positive,organism,antibiotic,susceptibility
0,AC13886383,1000320495,2100450314,2008-01-16 18:30:00,Outpatient,BLOOD,0,Null,Null,Null
1,AC13886383,1000320495,2100450315,2008-01-16 18:30:00,Outpatient,BLOOD,0,Null,Null,Null
2,JJ80389552,1000320496,2100450316,2005-10-25 16:39:00,Outpatient,URINE,0,Null,Null,Null
3,EX31305827,1000320497,2100450317,2009-03-09 09:34:00,Inpatient,URINE,0,Null,Null,Null
4,GI26152696,1000320498,2100450318,2007-05-01 09:59:00,Outpatient,URINE,0,Null,Null,Null

================================================================================
DEMOGRAPHICS DATA
Columns: ['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'age', 'gender']

First 5 rows:

      anon_id  pat_enc_csn_id_coded  order_proc_id_coded    age  gender
0  AC13886383            1000320495           2100450314  65-74       1
1  AC13886383            1000320495           2100450315  65-74       1
2  JJ80389552            1000320496           2100450316  25-34       0
3  EX31305827            1000320497           2100450317  45-54       0
4  GI26152696            1000320498           2100450318  45-54       0

In [4]:
# Load the complete datasets

cultures = pd.read_csv(culture_file)
demographics = pd.read_csv(demographics_file)

print("CULTURE DATASET")
print("Rows:", cultures.shape[0])
print("Columns:", cultures.shape[1])

print("\nDEMOGRAPHICS DATASET")
print("Rows:", demographics.shape[0])
print("Columns:", demographics.shape[1])

CULTURE DATASET
Rows: 1893548
Columns: 10

DEMOGRAPHICS DATASET
Rows: 774149
Columns: 5

C:\Users\Administrator\AppData\Local\Temp\ipykernel_26124\2757561750.py:4: DtypeWarning: Columns (4: gender) have mixed types. Specify dtype option on import or set low_memory=False.
  demographics = pd.read_csv(demographics_file)

In [5]:
print("CULTURE COLUMNS")
print(cultures.columns.tolist())

print("\n" + "=" * 80)

print("DEMOGRAPHICS COLUMNS")
print(demographics.columns.tolist())

CULTURE COLUMNS
['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'order_time_jittered', 'ordering_mode', 'culture_description', 'was_positive', 'organism', 'antibiotic', 'susceptibility']

================================================================================
DEMOGRAPHICS COLUMNS
['anon_id', 'pat_enc_csn_id_coded', 'order_proc_id_coded', 'age', 'gender']

In [6]:
print("CULTURE DATA TYPES")
display(cultures.dtypes)

print("\n" + "=" * 80)

print("DEMOGRAPHICS DATA TYPES")
display(demographics.dtypes)

CULTURE DATA TYPES

anon_id                   str
pat_enc_csn_id_coded    int64
order_proc_id_coded     int64
order_time_jittered       str
ordering_mode             str
culture_description       str
was_positive            int64
organism                  str
antibiotic                str
susceptibility            str
dtype: object

================================================================================
DEMOGRAPHICS DATA TYPES

anon_id                    str
pat_enc_csn_id_coded     int64
order_proc_id_coded      int64
age                        str
gender                  object
dtype: object

In [7]:
print("CULTURE DATASET — MISSING VALUES")
print(cultures.isnull().sum())

print("\nDEMOGRAPHICS DATASET — MISSING VALUES")
print(demographics.isnull().sum())

CULTURE DATASET — MISSING VALUES
anon_id                 0
pat_enc_csn_id_coded    0
order_proc_id_coded     0
order_time_jittered     0
ordering_mode           0
culture_description     0
was_positive            0
organism                0
antibiotic              0
susceptibility          0
dtype: int64

DEMOGRAPHICS DATASET — MISSING VALUES
anon_id                 0
pat_enc_csn_id_coded    0
order_proc_id_coded     0
age                     0
gender                  0
dtype: int64

In [8]:
print("CULTURE DATASET — DUPLICATE ROWS")
print("Duplicate rows:", cultures.duplicated().sum())

print("\nDEMOGRAPHICS DATASET — DUPLICATE ROWS")
print("Duplicate rows:", demographics.duplicated().sum())

CULTURE DATASET — DUPLICATE ROWS
Duplicate rows: 16536

DEMOGRAPHICS DATASET — DUPLICATE ROWS
Duplicate rows: 0

In [9]:
duplicate_rows = cultures[cultures.duplicated(keep=False)]

print("Total rows involved in duplicates:", len(duplicate_rows))

display(duplicate_rows.head(20))

Total rows involved in duplicates: 32728

,anon_id,pat_enc_csn_id_coded,order_proc_id_coded,order_time_jittered,ordering_mode,culture_description,was_positive,organism,antibiotic,susceptibility
4440,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
4441,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
4442,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Susceptible
4443,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Susceptible
4444,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Susceptible
4445,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Susceptible
4446,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Susceptible
4447,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Susceptible
4448,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
4449,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
4450,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Susceptible
4451,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Susceptible
4452,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Susceptible
4453,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Susceptible
4454,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
4455,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
4456,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Susceptible
4457,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Susceptible
4458,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin rm,Resistant
4459,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin rm,Resistant

In [10]:
duplicate_groups = cultures[cultures.duplicated(keep=False)].drop_duplicates()

print("Number of unique duplicated records:", len(duplicate_groups))

Number of unique duplicated records: 16192

In [11]:
print("How many times do duplicated records occur?")
print(
    cultures.value_counts()
    .loc[lambda x: x > 1]
    .value_counts()
    .sort_index()
)

How many times do duplicated records occur?
count
2    15858
3      324
4       10
Name: count, dtype: int64

In [12]:
display(duplicate_groups.head(20))

,anon_id,pat_enc_csn_id_coded,order_proc_id_coded,order_time_jittered,ordering_mode,culture_description,was_positive,organism,antibiotic,susceptibility
4440,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
4442,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Susceptible
4444,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Susceptible
4446,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Susceptible
4448,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
4450,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Susceptible
4452,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Susceptible
4454,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
4456,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Susceptible
4458,YU3495620,1000322575,2100452906,2008-12-01 17:43:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin rm,Resistant
4595,IQ06436246,1000322625,2100452985,2009-08-26 16:38:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Resistant
4596,IQ06436246,1000322625,2100452985,2009-08-26 16:38:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant
4597,IQ06436246,1000322625,2100452985,2009-08-26 16:38:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Susceptible
4600,IQ06436246,1000322625,2100452985,2009-08-26 16:38:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant
4602,IQ06436246,1000322625,2100452985,2009-08-26 16:38:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Susceptible
4603,IQ06436246,1000322625,2100452985,2009-08-26 16:38:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin rm,Susceptible
4608,IQ06436246,1000322625,2100452985,2009-08-26 16:38:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Resistant
4610,IQ06436246,1000322625,2100452985,2009-08-26 16:38:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Resistant
4906,UH30066754,1000322787,2100453194,2009-07-05 22:31:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Intermediate
4908,UH30066754,1000322787,2100453194,2009-07-05 22:31:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant

In [13]:
duplicate_counts = (
    cultures
    .value_counts()
    .reset_index(name="duplicate_count")
)

duplicate_counts = duplicate_counts[
    duplicate_counts["duplicate_count"] > 1
]

display(duplicate_counts.head(10))

,anon_id,pat_enc_csn_id_coded,order_proc_id_coded,order_time_jittered,ordering_mode,culture_description,was_positive,organism,antibiotic,susceptibility,duplicate_count
0,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant,4
1,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant,4
2,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant,4
3,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant,4
4,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant,4
5,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant,4
6,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant,4
7,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible,4
8,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant,4
9,BV561977,1000081837,2100113783,2012-03-29 19:58:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Resistant,4

In [14]:
# Inspect one duplicate group in detail

example_duplicate = cultures[
    (cultures["anon_id"] == "LK34832465") &
    (cultures["pat_enc_csn_id_coded"] == 1000009908) &
    (cultures["order_proc_id_coded"] == 2100013731)
]

display(example_duplicate)

,anon_id,pat_enc_csn_id_coded,order_proc_id_coded,order_time_jittered,ordering_mode,culture_description,was_positive,organism,antibiotic,susceptibility
185803,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
185804,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,STAPHYLOCOCCUS AUREUS,Ampicillin/sulbactam,Susceptible
185805,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant
185806,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,STAPHYLOCOCCUS AUREUS,Clindamycin,Resistant
185807,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant
185808,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,STAPHYLOCOCCUS AUREUS,Erythromycin,Resistant
185809,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant
185810,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,STAPHYLOCOCCUS AUREUS,Gentamicin,Susceptible
185811,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant
185812,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,STAPHYLOCOCCUS AUREUS,Oxacillin,Susceptible
185813,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
185814,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,STAPHYLOCOCCUS AUREUS,Tetracycline,Susceptible
185815,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Resistant
185816,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,STAPHYLOCOCCUS AUREUS,Trimeth/sulf,Susceptible
185817,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant
185818,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,STAPHYLOCOCCUS AUREUS,Vancomycin,Susceptible
185819,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
185820,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
185821,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Resistant
185822,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant
185823,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant
185824,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant
185825,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
185826,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant
185827,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant
185828,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant
185829,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant
185830,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
185831,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant
185832,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Susceptible
185833,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant
185834,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant
185835,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
185836,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
185837,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Resistant
185838,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Resistant
185839,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant
185840,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant
185841,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
185842,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Resistant
185843,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant
185844,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
185845,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant
185846,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant
185847,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant
185848,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant
185849,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
185850,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Resistant
185851,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant
185852,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
185853,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant

In [15]:
exact_duplicates_in_order = example_duplicate[
    example_duplicate.duplicated(keep=False)
]

print("Exact duplicate rows in this order:",
      len(exact_duplicates_in_order))

display(exact_duplicates_in_order)

Exact duplicate rows in this order: 42

,anon_id,pat_enc_csn_id_coded,order_proc_id_coded,order_time_jittered,ordering_mode,culture_description,was_positive,organism,antibiotic,susceptibility
185803,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
185805,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant
185807,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant
185809,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant
185811,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant
185813,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
185815,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Resistant
185817,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant
185819,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
185820,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
185821,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Resistant
185822,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant
185823,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant
185824,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant
185825,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
185826,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant
185827,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant
185828,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant
185829,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant
185830,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
185831,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant
185833,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant
185834,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant
185835,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
185836,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
185837,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Resistant
185838,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Resistant
185839,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant
185840,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant
185841,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
185842,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Resistant
185843,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant
185844,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant
185845,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant
185846,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant
185847,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant
185848,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant
185849,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant
185850,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Resistant
185851,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant
185852,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible
185853,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant

In [16]:
print("Total rows in this order:", len(example_duplicate))
print("Unique rows in this order:", len(example_duplicate.drop_duplicates()))

Total rows in this order: 51
Unique rows in this order: 20

In [17]:
duplicate_counts_in_order = (
    example_duplicate
    .value_counts()
    .reset_index(name="duplicate_count")
)

display(
    duplicate_counts_in_order[
        duplicate_counts_in_order["duplicate_count"] > 1
    ]
)

,anon_id,pat_enc_csn_id_coded,order_proc_id_coded,order_time_jittered,ordering_mode,culture_description,was_positive,organism,antibiotic,susceptibility,duplicate_count
0,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant,4
1,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant,4
2,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant,4
3,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant,4
4,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant,4
5,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant,4
6,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant,4
7,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible,4
8,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant,4
9,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Resistant,3
10,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcil/clavulanate,Resistant,3

In [19]:
print("CULTURE DATASET — 'Null' VALUES")
display((cultures == "Null").sum())

print("\n" + "=" * 80)

print("DEMOGRAPHICS DATASET — 'Null' VALUES")
display((demographics == "Null").sum())

CULTURE DATASET — 'Null' VALUES

anon_id                      0
pat_enc_csn_id_coded         0
order_proc_id_coded          0
order_time_jittered          0
ordering_mode              655
culture_description          0
was_positive                 0
organism                697713
antibiotic              687460
susceptibility          693030
dtype: int64

================================================================================
DEMOGRAPHICS DATASET — 'Null' VALUES

anon_id                  0
pat_enc_csn_id_coded     0
order_proc_id_coded      0
age                      0
gender                  63
dtype: int64

In [20]:
print("CULTURE DATASET — DUPLICATE ROWS")
print("Duplicate rows:", cultures.duplicated().sum())

print("\nDEMOGRAPHICS DATASET — DUPLICATE ROWS")
print("Duplicate rows:", demographics.duplicated().sum())

CULTURE DATASET — DUPLICATE ROWS
Duplicate rows: 16536

DEMOGRAPHICS DATASET — DUPLICATE ROWS
Duplicate rows: 0

In [21]:
duplicate_rows = cultures[cultures.duplicated(keep=False)]

print("Total rows involved in duplicate groups:", len(duplicate_rows))

display(
    duplicate_rows.sort_values(
        by=["anon_id", "order_proc_id_coded", "antibiotic"]
    ).head(20)
)

Total rows involved in duplicate groups: 32728

,anon_id,pat_enc_csn_id_coded,order_proc_id_coded,order_time_jittered,ordering_mode,culture_description,was_positive,organism,antibiotic,susceptibility
1885399,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Susceptible
1885409,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Susceptible
1885400,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Susceptible
1885410,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Susceptible
1885401,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Susceptible
1885411,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Susceptible
1885402,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Susceptible
1885412,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Susceptible
1885403,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Susceptible
1885413,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Susceptible
1885404,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Susceptible
1885414,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Susceptible
1885405,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Susceptible
1885415,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Susceptible
1885406,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Meropenem,Susceptible
1885416,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Meropenem,Susceptible
1885407,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Piperacillin/tazobactam,Susceptible
1885417,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Piperacillin/tazobactam,Susceptible
1885408,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Susceptible
1885418,AA78113815,1000318107,2100446868,2023-11-16 10:54:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Susceptible

In [22]:
duplicate_counts = (
    cultures
    .groupby(cultures.columns.tolist(), dropna=False)
    .size()
    .reset_index(name="repeat_count")
)

print("Number of unique records:", len(duplicate_counts))

print("\nMost frequently repeated exact records:")
display(
    duplicate_counts
    .sort_values("repeat_count", ascending=False)
    .head(20)
)

Number of unique records: 1877012

Most frequently repeated exact records:

,anon_id,pat_enc_csn_id_coded,order_proc_id_coded,order_time_jittered,ordering_mode,culture_description,was_positive,organism,antibiotic,susceptibility,repeat_count
853951,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Pip/tazobactam,Susceptible,4
853943,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Resistant,4
853945,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ceftazidime,Resistant,4
853944,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Cefepime,Resistant,4
853953,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant,4
853947,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant,4
142666,BV561977,1000081837,2100113783,2012-03-29 19:58:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Imipenem,Resistant,4
853946,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ciprofloxacin,Resistant,4
853942,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant,4
853950,LK34832465,1000009908,2100013731,2013-03-30 10:00:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Levofloxacin,Resistant,4
135361,BT2168846,1000322891,2100453321,2009-05-13 23:17:00,Inpatient,RESPIRATORY,1,ACHROMOBACTER XYLOSOXIDANS,Ceftazidime,Susceptible,3
53115,AR4959829,1000423116,2100581381,2019-07-17 12:35:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Susceptible,3
856618,LL2956948,1000005015,2100006977,2013-01-13 09:19:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Susceptible,3
135362,BT2168846,1000322891,2100453321,2009-05-13 23:17:00,Inpatient,RESPIRATORY,1,ACHROMOBACTER XYLOSOXIDANS,Gentamicin,Resistant,3
142664,BV561977,1000081837,2100113783,2012-03-29 19:58:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Gentamicin,Resistant,3
142651,BV561977,1000081837,2100113783,2012-03-29 19:58:00,Inpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Amikacin,Resistant,3
135366,BT2168846,1000322891,2100453321,2009-05-13 23:17:00,Inpatient,RESPIRATORY,1,ACHROMOBACTER XYLOSOXIDANS,Pip/tazobactam,Susceptible,3
761374,KE2259065,1000414278,2100569466,2019-04-04 15:31:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Ticarcillin-clavulanic acid,Null,3
761375,KE2259065,1000414278,2100569466,2019-04-04 15:31:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Tobramycin,Resistant,3
810073,KU2787545,1000361606,2100500293,2008-10-10 02:02:00,Outpatient,RESPIRATORY,1,PSEUDOMONAS AERUGINOSA,Aztreonam,Susceptible,3

In [23]:
print("REPEAT COUNT DISTRIBUTION")

repeat_distribution = (
    duplicate_counts["repeat_count"]
    .value_counts()
    .sort_index()
)

display(repeat_distribution)

REPEAT COUNT DISTRIBUTION

repeat_count
1    1860820
2      15858
3        324
4         10
Name: count, dtype: int64

In [24]:
# Check whether duplicate records occur within the same culture order

duplicate_rows = cultures[cultures.duplicated(keep=False)]

print("Number of duplicate rows:", len(duplicate_rows))

print("\nNumber of unique culture orders containing duplicates:")
print(duplicate_rows["order_proc_id_coded"].nunique())

print("\nNumber of unique patients containing duplicates:")
print(duplicate_rows["anon_id"].nunique())

Number of duplicate rows: 32728

Number of unique culture orders containing duplicates:
2204

Number of unique patients containing duplicates:
729

In [25]:
print("ORDERING MODE")
print(cultures["ordering_mode"].value_counts(dropna=False))

print("\n" + "=" * 60)

print("CULTURE DESCRIPTION")
print(cultures["culture_description"].value_counts(dropna=False))

print("\n" + "=" * 60)

print("WAS POSITIVE")
print(cultures["was_positive"].value_counts(dropna=False))

print("\n" + "=" * 60)

print("SUSCEPTIBILITY")
print(cultures["susceptibility"].value_counts(dropna=False))

ORDERING MODE
ordering_mode
Inpatient     1064782
Outpatient     828111
Null              655
Name: count, dtype: int64

============================================================
CULTURE DESCRIPTION
culture_description
URINE          1360633
BLOOD           353138
RESPIRATORY     179777
Name: count, dtype: int64

============================================================
WAS POSITIVE
was_positive
1    1220485
0     673063
Name: count, dtype: int64

============================================================
SUSCEPTIBILITY
susceptibility
Susceptible     955031
Null            693030
Resistant       200735
Intermediate     43458
Inconclusive      1294
Name: count, dtype: int64

In [26]:
print("ALL SUSCEPTIBILITY VALUES")
print(cultures["susceptibility"].value_counts(dropna=False).to_string())

ALL SUSCEPTIBILITY VALUES
susceptibility
Susceptible     955031
Null            693030
Resistant       200735
Intermediate     43458
Inconclusive      1294

In [27]:
print("TOP ORGANISMS")
print(cultures["organism"].value_counts(dropna=False).head(30).to_string())

TOP ORGANISMS
organism
Null                                           697713
ESCHERICHIA COLI                               594694
KLEBSIELLA PNEUMONIAE                          141760
PSEUDOMONAS AERUGINOSA                         113534
ENTEROCOCCUS FAECALIS                           50168
PROTEUS MIRABILIS                               48573
STAPHYLOCOCCUS AUREUS                           30140
METHICILLIN RESISTANT STAPHYLOCOCCUS AUREUS     22603
STAPHYLOCOCCUS EPIDERMIDIS                      22097
ESBL ESCHERICHIA COLI                           17925
KLEBSIELLA OXYTOCA                              14262
CITROBACTER FREUNDII COMPLEX                    12976
ENTEROBACTER CLOACAE COMPLEX                    12199
CITROBACTER KOSERI                              10686
ENTEROBACTER CLOACAE                             7530
KLEBSIELLA VARIICOLA                             7416
KLEBSIELLA AEROGENES                             6745
ENTEROCOCCUS FAECIUM                             6558
SERRATIA MARCESCENS                              6389
MORGANELLA MORGANII                              5840
ACHROMOBACTER SPECIES                            5586
ENTEROBACTER AEROGENES                           5162
ESBL KLEBSIELLA PNEUMONIAE                       4483
STAPHYLOCOCCUS SPECIES COAGULASE NEGATIVE        4339
STENOTROPHOMONAS MALTOPHILIA                     2203
PROVIDENCIA STUARTII                             2111
ACHROMOBACTER XYLOSOXIDANS                       1896
MYCOBACTERIUM ABSCESSUS                          1817
PROTEUS VULGARIS GROUP                           1395
STAPHYLOCOCCUS HAEMOLYTICUS                      1270

In [28]:
print("UNIQUE ORGANISMS")
print("Total unique organism values:", cultures["organism"].nunique(dropna=False))

UNIQUE ORGANISMS
Total unique organism values: 396

In [29]:
print("\nNON-NULL UNIQUE ORGANISMS")
print("Unique organisms excluding Null:",
      cultures["organism"].nunique(dropna=True))

NON-NULL UNIQUE ORGANISMS
Unique organisms excluding Null: 396

In [30]:
print("TOP ANTIBIOTICS")
print(
    cultures["antibiotic"]
    .value_counts(dropna=False)
    .head(30)
    .to_string()
)

TOP ANTIBIOTICS
antibiotic
Null                             687460
Gentamicin                        82109
Levofloxacin                      73413
Ciprofloxacin                     73081
Tobramycin                        67538
Nitrofurantoin                    64364
Meropenem                         64223
Ampicillin                        56197
Ampicillin/sulbactam              51026
Aztreonam                         49875
Tetracycline                      48775
Ceftriaxone                       48693
Ertapenem                         48661
Cefepime                          47663
Cefazolin                         42975
Trimeth/sulf                      39297
Cefuroxime                        39150
Trimethoprim/sulfamethoxazole     34981
Piperacillin/tazobactam           33528
Pip/tazobactam                    33097
Imipenem                          24349
Amoxicillin/clavulanic acid       24166
Cefotaxime                        22515
Vancomycin                        21649
Ceftazidime                       20979
Amikacin                          18795
Oxacillin                         13185
Amox/clavulanate                  10039
Clindamycin                        8713
Cephalothin                        8238

In [31]:
print("UNIQUE ANTIBIOTICS")
print(
    "Total unique antibiotic values:",
    cultures["antibiotic"].nunique(dropna=False)
)

print(
    "Unique antibiotics excluding Null:",
    cultures["antibiotic"].nunique(dropna=True)
)

UNIQUE ANTIBIOTICS
Total unique antibiotic values: 80
Unique antibiotics excluding Null: 80

In [32]:
print("ROWS PER CULTURE ORDER")

rows_per_order = cultures.groupby("order_proc_id_coded").size()

print(rows_per_order.describe())

print("\nMaximum rows for one culture order:",
      rows_per_order.max())

ROWS PER CULTURE ORDER
count    774149.000000
mean          2.445974
std           4.564526
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         102.000000
dtype: float64

Maximum rows for one culture order: 102

In [33]:
print("\nCULTURE ORDERS WITH MOST ROWS")

print(
    rows_per_order
    .sort_values(ascending=False)
    .head(10)
)

CULTURE ORDERS WITH MOST ROWS
order_proc_id_coded
2100297034    102
2100297035     81
2100577530     62
2100767505     58
2100422819     56
2100135747     55
2100363042     53
2100557950     53
2100597893     53
2100540847     53
dtype: int64

In [34]:
order_id = 2100297034

order_data = cultures[
    cultures["order_proc_id_coded"] == order_id
]

print("Rows in this culture order:", len(order_data))

print("\nUnique organisms:",
      order_data["organism"].nunique())

print("Unique antibiotics:",
      order_data["antibiotic"].nunique())

print("\nOrganism distribution:")
print(order_data["organism"].value_counts(dropna=False).to_string())

print("\nAntibiotic distribution:")
print(order_data["antibiotic"].value_counts(dropna=False).to_string())

Rows in this culture order: 102

Unique organisms: 8
Unique antibiotics: 15

Organism distribution:
organism
ESCHERICHIA COLI          14
PROTEUS MIRABILIS         14
PROVIDENCIA SPECIES       14
KLEBSIELLA PNEUMONIAE     13
PROTEUS VULGARIS GROUP    13
RAOULTELLA PLANTICOLA     13
MORGANELLA MORGANII       12
ESBL ESCHERICHIA COLI      9

Antibiotic distribution:
antibiotic
Ampicillin/sulbactam             8
Ciprofloxacin                    8
Ertapenem                        8
Gentamicin                       8
Levofloxacin                     8
Meropenem                        8
Piperacillin/tazobactam          8
Tobramycin                       8
Trimethoprim/sulfamethoxazole    8
Aztreonam                        7
Cefepime                         7
Ceftriaxone                      7
Cefazolin                        5
Ampicillin                       3
Amikacin                         1

In [35]:
display(
    order_data[
        [
            "anon_id",
            "pat_enc_csn_id_coded",
            "order_proc_id_coded",
            "culture_description",
            "was_positive",
            "organism",
            "antibiotic",
            "susceptibility"
        ]
    ].sort_values(["organism", "antibiotic"])
)

,anon_id,pat_enc_csn_id_coded,order_proc_id_coded,culture_description,was_positive,organism,antibiotic,susceptibility
1522813,PA26889460,1000210986,2100297034,BLOOD,1,ESBL ESCHERICHIA COLI,Ampicillin/sulbactam,Null
1522814,PA26889460,1000210986,2100297034,BLOOD,1,ESBL ESCHERICHIA COLI,Ciprofloxacin,Susceptible
1522815,PA26889460,1000210986,2100297034,BLOOD,1,ESBL ESCHERICHIA COLI,Ertapenem,Susceptible
1522816,PA26889460,1000210986,2100297034,BLOOD,1,ESBL ESCHERICHIA COLI,Gentamicin,Susceptible
1522817,PA26889460,1000210986,2100297034,BLOOD,1,ESBL ESCHERICHIA COLI,Levofloxacin,Susceptible
...,...,...,...,...,...,...,...,...
1522896,PA26889460,1000210986,2100297034,BLOOD,1,RAOULTELLA PLANTICOLA,Levofloxacin,Susceptible
1522897,PA26889460,1000210986,2100297034,BLOOD,1,RAOULTELLA PLANTICOLA,Meropenem,Susceptible
1522898,PA26889460,1000210986,2100297034,BLOOD,1,RAOULTELLA PLANTICOLA,Piperacillin/tazobactam,Susceptible
1522899,PA26889460,1000210986,2100297034,BLOOD,1,RAOULTELLA PLANTICOLA,Tobramycin,Susceptible
1522900,PA26889460,1000210986,2100297034,BLOOD,1,RAOULTELLA PLANTICOLA,Trimethoprim/sulfamethoxazole,Susceptible

In [36]:
print("DATE RANGE")

cultures["order_time_jittered"] = pd.to_datetime(
    cultures["order_time_jittered"],
    errors="coerce"
)

print("Earliest culture/order:", cultures["order_time_jittered"].min())
print("Latest culture/order:", cultures["order_time_jittered"].max())

print("\nMissing dates:")
print(cultures["order_time_jittered"].isna().sum())

DATE RANGE
Earliest culture/order: 2004-12-01 14:13:00
Latest culture/order: 2025-02-28 08:33:00

Missing dates:
0

In [37]:
print("\nYEAR DISTRIBUTION")

print(
    cultures["order_time_jittered"]
    .dt.year
    .value_counts()
    .sort_index()
)

YEAR DISTRIBUTION
order_time_jittered
2004       132
2005      4933
2006     18067
2007     31925
2008     39919
2009     51683
2010     50354
2011     58685
2012     70934
2013     85622
2014     88771
2015    103065
2016    117080
2017    126409
2018    136852
2019    144517
2020    120004
2021    143793
2022    157615
2023    167526
2024    165581
2025     10081
Name: count, dtype: int64

In [38]:
print("UNIQUE IDENTIFIERS")

print("Unique patients (anon_id):",
      cultures["anon_id"].nunique())

print("Unique encounters (pat_enc_csn_id_coded):",
      cultures["pat_enc_csn_id_coded"].nunique())

print("Unique culture orders (order_proc_id_coded):",
      cultures["order_proc_id_coded"].nunique())

UNIQUE IDENTIFIERS
Unique patients (anon_id): 237258
Unique encounters (pat_enc_csn_id_coded): 566969
Unique culture orders (order_proc_id_coded): 774149

In [39]:
print("\nPATIENTS PER ENCOUNTER")

patients_per_encounter = (
    cultures.groupby("pat_enc_csn_id_coded")["anon_id"]
    .nunique()
)

print(patients_per_encounter.describe())
print("Maximum patients per encounter:",
      patients_per_encounter.max())

PATIENTS PER ENCOUNTER
count    566969.0
mean          1.0
std           0.0
min           1.0
25%           1.0
50%           1.0
75%           1.0
max           1.0
Name: anon_id, dtype: float64
Maximum patients per encounter: 1

In [40]:
print("\nENCOUNTERS PER PATIENT")

encounters_per_patient = (
    cultures.groupby("anon_id")["pat_enc_csn_id_coded"]
    .nunique()
)

print(encounters_per_patient.describe())
print("Maximum encounters for one patient:",
      encounters_per_patient.max())

ENCOUNTERS PER PATIENT
count    237258.000000
mean          2.389673
std           3.324591
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max         124.000000
Name: pat_enc_csn_id_coded, dtype: float64
Maximum encounters for one patient: 124

In [41]:
print("CULTURE ORDERS PER PATIENT")

orders_per_patient = (
    cultures.groupby("anon_id")["order_proc_id_coded"]
    .nunique()
)

print(orders_per_patient.describe())

print(
    "\nMaximum culture orders for one patient:",
    orders_per_patient.max()
)

CULTURE ORDERS PER PATIENT
count    237258.000000
mean          3.262899
std           5.113853
min           1.000000
25%           1.000000
50%           2.000000
75%           3.000000
max         181.000000
Name: order_proc_id_coded, dtype: float64

Maximum culture orders for one patient: 181

In [42]:
print("\nPATIENTS WITH MOST CULTURE ORDERS")

print(
    orders_per_patient
    .sort_values(ascending=False)
    .head(10)
)

PATIENTS WITH MOST CULTURE ORDERS
anon_id
DI0526977     181
MU6329168     137
RN5318764     134
JR48002134    129
UN05952425    128
KE4176587     126
FU9254096     126
CI21296921    124
PA07207836    123
PX15432076    122
Name: order_proc_id_coded, dtype: int64

In [43]:
print("DEMOGRAPHICS DATASET — AGE")
print(demographics["age"].describe())

print("\n" + "=" * 70)

print("AGE VALUE COUNTS — TOP 20")
print(demographics["age"].value_counts(dropna=False).head(20))

print("\n" + "=" * 70)

print("GENDER DISTRIBUTION")
print(demographics["gender"].value_counts(dropna=False))

DEMOGRAPHICS DATASET — AGE
count     774149
unique         9
top        65-74
freq      149570
Name: age, dtype: object

======================================================================
AGE VALUE COUNTS — TOP 20
age
65-74       149570
55-64       136308
25-34       118305
45-54       103423
35-44        98151
75-84        90164
18-24        42767
85-89        21719
above 90     13742
Name: count, dtype: int64

======================================================================
GENDER DISTRIBUTION
gender
0       406841
1       236173
0        84743
1        46329
Null        63
Name: count, dtype: int64

In [44]:
print("UNIQUE AGE VALUES")
print("Number of unique age values:", demographics["age"].nunique(dropna=False))

print("\nUNIQUE GENDER VALUES")
print("Number of unique gender values:", demographics["gender"].nunique(dropna=False))

print("\nGender values:")
print(demographics["gender"].unique())

UNIQUE AGE VALUES
Number of unique age values: 9

UNIQUE GENDER VALUES
Number of unique gender values: 5

Gender values:
[1 0 '1' '0' 'Null']

In [45]:
print("DEMOGRAPHICS IDENTIFIERS")

print("Unique patients:",
      demographics["anon_id"].nunique())

print("Unique encounters:",
      demographics["pat_enc_csn_id_coded"].nunique())

print("Unique culture orders:",
      demographics["order_proc_id_coded"].nunique())

DEMOGRAPHICS IDENTIFIERS
Unique patients: 237258
Unique encounters: 566969
Unique culture orders: 774149

In [46]:
culture_orders = set(cultures["order_proc_id_coded"].unique())
demographics_orders = set(demographics["order_proc_id_coded"].unique())

print("CULTURE ORDERS:", len(culture_orders))
print("DEMOGRAPHICS ORDERS:", len(demographics_orders))

print("\nORDERS PRESENT IN BOTH:")
print(len(culture_orders & demographics_orders))

print("\nORDERS ONLY IN CULTURE DATA:")
print(len(culture_orders - demographics_orders))

print("\nORDERS ONLY IN DEMOGRAPHICS DATA:")
print(len(demographics_orders - culture_orders))

CULTURE ORDERS: 774149
DEMOGRAPHICS ORDERS: 774149

ORDERS PRESENT IN BOTH:
774149

ORDERS ONLY IN CULTURE DATA:
0

ORDERS ONLY IN DEMOGRAPHICS DATA:
0

In [47]:
print("ORDER-LEVEL MATCH RATE")

matched_orders = len(culture_orders & demographics_orders)

match_rate = matched_orders / len(culture_orders) * 100

print(f"Matched culture orders: {matched_orders:,}")
print(f"Match rate: {match_rate:.2f}%")

ORDER-LEVEL MATCH RATE
Matched culture orders: 774,149
Match rate: 100.00%

In [48]:
print("ROWS PER ORGANISM WITHIN CULTURE ORDERS")

organism_per_order = (
    cultures.groupby("order_proc_id_coded")["organism"]
    .nunique(dropna=True)
)

print(organism_per_order.describe())

print("\nMaximum organisms in one culture order:",
      organism_per_order.max())

ROWS PER ORGANISM WITHIN CULTURE ORDERS
count    774149.000000
mean          1.014449
std           0.130006
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           8.000000
Name: organism, dtype: float64

Maximum organisms in one culture order: 8

In [49]:
print("ROWS PER ANTIBIOTIC WITHIN CULTURE ORDERS")

antibiotic_per_order = (
    cultures.groupby("order_proc_id_coded")["antibiotic"]
    .nunique(dropna=True)
)

print(antibiotic_per_order.describe())

print("\nMaximum antibiotics in one culture order:",
      antibiotic_per_order.max())

ROWS PER ANTIBIOTIC WITHIN CULTURE ORDERS
count    774149.000000
mean          2.342466
std           4.111340
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          27.000000
Name: antibiotic, dtype: float64

Maximum antibiotics in one culture order: 27

In [52]:
print("ORGANISM + ANTIBIOTIC COMBINATIONS")

combination_counts = (
    cultures[["order_proc_id_coded", "organism", "antibiotic"]]
    .dropna()
    .drop_duplicates()
    .groupby("order_proc_id_coded")
    .size()
)

print(combination_counts.describe())

print(
    "\nMaximum organism-antibiotic combinations in one order:",
    combination_counts.max()
)

ORGANISM + ANTIBIOTIC COMBINATIONS
count    774149.000000
mean          2.414556
std           4.437884
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         102.000000
dtype: float64

Maximum organism-antibiotic combinations in one order: 102

# Data Dictionary

## 1. Culture Dataset

| Column | Meaning | Data Role |
|---|---|---|
| anon_id | Deidentified patient identifier | Patient identifier |
| pat_enc_csn_id_coded | Deidentified patient encounter number | Encounter identifier |
| order_proc_id_coded | Deidentified unique culture order number | Culture-order identifier |
| order_time_jittered | Jittered timestamp associated with the culture order | Temporal variable |
| ordering_mode | Mode in which the culture was ordered | Clinical/order feature |
| culture_description | Type of culture ordered, such as Blood, Respiratory, or Urine | Culture feature |
| was_positive | Binary indicator of whether the culture result was positive | Culture outcome |
| organism | Name of microorganism identified | Microbiological feature |
| antibiotic | Antibiotic tested | Susceptibility feature |
| susceptibility | Susceptibility result for the tested antibiotic | Resistance outcome |

## Important Dataset Notes

- The dataset is deidentified.
- Missing values are represented by the literal value `"Null"` according to the dataset README.
- Dates and times have been jittered.
- A single culture order can contain multiple rows.
- A single culture order can contain multiple organisms and/or antibiotics.
- Susceptibility is recorded at the antibiotic-testing level.

## 2. Demographics Dataset

| Column | Meaning | Data Role |
|---|---|---|
| anon_id | Deidentified patient identifier | Patient identifier |
| pat_enc_csn_id_coded | Deidentified patient encounter number | Encounter identifier |
| order_proc_id_coded | Deidentified unique culture order number | Culture-order identifier |
| age | Patient age represented as an age group | Demographic feature |
| gender | Binary gender indicator; the dataset does not identify which value represents which gender | Demographic feature |

## Important Dataset Notes

- Age is grouped into categories rather than provided as an exact age.
- Gender is represented by binary indicators.
- The dataset documentation does not identify which binary value corresponds to which gender.
- `"Null"` represents missing information in the source dataset.

## 3. Project-Level Data Dictionary

This section maps the available variables to their role in the healthcare analytics and antimicrobial resistance prediction project.

| Variable | Source Dataset | Project Role | ML Consideration |
|---|---|---|---|
| anon_id | Culture + Demographics | Patient identifier | Identifier; not used directly as a predictor |
| pat_enc_csn_id_coded | Culture + Demographics | Encounter identifier | Identifier; not used directly as a predictor |
| order_proc_id_coded | Culture + Demographics | Culture-order identifier | Identifier; used to define the analysis unit |
| order_time_jittered | Culture | Culture timing | Potential temporal feature; timestamps must respect prediction timing |
| ordering_mode | Culture | Clinical/order feature | Potential predictor |
| culture_description | Culture | Type of microbiological culture | Potential predictor |
| was_positive | Culture | Culture positivity outcome | Analytics variable; potential secondary outcome |
| organism | Culture | Identified microorganism | Requires careful timing assessment before ML use |
| antibiotic | Culture | Antibiotic tested | Context variable for susceptibility analysis |
| susceptibility | Culture | Antibiotic susceptibility result | Primary resistance-related outcome |
| age | Demographics | Patient age group | Potential predictor |
| gender | Demographics | Binary demographic indicator | Potential predictor; coding meaning is not identified |

### Project Data Rules

- Patient, encounter, and culture-order identifiers will not be used as predictive features.
- The susceptibility result represents the resistance-related outcome and must not be used as an input feature when predicting that outcome.
- Variables will only be used as ML predictors if they would be available at the defined prediction point.
- Organism information requires a timing assessment because organism identification may occur during the microbiology workflow.
- The final ML feature set will be determined after the dataset structure and prediction timeline are fully investigated.
- No AMR target definition will be finalized until the susceptibility data and relevant clinical variables have been examined.

In [2]:
print("SUSCEPTIBILITY VALUES")
print(culture["susceptibility"].value_counts(dropna=False))

SUSCEPTIBILITY VALUES

NameError: name 'culture' is not defined